#Grab the latest alpine image
FROM ubuntu:latest

# Install python and pip
#RUN apk add py-cryptography
#RUN apk add --no-cache --virtual .pynacl_deps build-base python3-dev libffi-dev

#RUN apk add --no-cache --update python3 py3-pip bash

RUN apt update -y
RUN apt install python3-pip -y

RUN pip3 install "moto[server]"

EXPOSE 8888

CMD ["moto_server","dynamodb2","-p8888", "-H", "0.0.0.0"]


