#Grab the latest alpine image
FROM ubuntu:latest

# Install python and pip
#RUN apk add --no-cache --update python3 py3-pip bash
RUN apt-get update
RUN apt-get -y install python3-pip
ADD ./requirements.txt /tmp/requirements.txt

# Install dependencies
RUN pip3 install --no-cache-dir -q -r  /tmp/requirements.txt

# Add our code
ADD ./ /opt/webapp/
WORKDIR /opt/webapp

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
# Expose is NOT supported by Heroku
#EXPOSE 8000

# Run the image as a non-root user
# RUN adduser -D myuser
# USER myuser

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0


# Run the app.  CMD is required to run on Heroku
#CMD gunicorn -w 4 wsgi

CMD ["flask", "run"]
